### PR TITLE
Don't import pybind11_cmake for non-build commands

### PR DESCRIPTION
**Pull request by bjodah**
I think this does the trick...

### CODE REVIEW

**Comment by safijari** [comment]
I may have misunderstood what setup_requires does. Is it meant to install the package if it doesn't exist? Neither `python setup.py build/install` nor `pip install .` are doing that.

If that's not the intent then things look good. I'm able to run `python setup.py --version` for example and not have it error out (though can't do `--name` or `--url`).

**Comment by bjodah** [comment]
No, it doesn't actually install them. But the rendered packages only need pybind11_cmake during the build phase right? If you look under "setup_requires" here you'll see that it explicitly says that the package is not installed:
https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords

**Comment by safijari** [comment]
It also says that if the same package is defined under `install_requires` then it'll be installed but I assume that will only happen during an actual installation?

**Comment by bjodah** [comment]
Yes, but will a user of "my_awesome_package" (which I write using `pybind11_cmake`) ever need `pybind11_cmake` after he/she has installated "my_awesome_package"?

**Comment by safijari** [comment]
They will not, that's a good point. Though they will still need it for the install assuming they're installing from source and not using a wheel but I suppose that's an edge case.

I'll merge this. I wanna fiddle with it a bit more after though to ensure more pip commands can run if needed and then I'll do a release to PyPI

**Comment by safijari** [comment]
Uhhhhh, GitHub shows this as my commit for some reason. I just merged the PR it should show up as yours :/

**Comment by safijari** [comment]
Oh wait nvmnd. It was just a weird merge since there were readme changes from me after. Your commit still shows correctly

**Comment by bjodah** [comment]
No worries :-) -- this is hardly a big contribution from me. 👍 But good
that things are in working order.

**Pull request merged**
